### ISSUE TITLE
Non-verbose build shows "-e"

### ISSUE THREAD

**Issue by mikrosk** [mikrosk/lib#18]
```
-e   CC       _gc_vq_vgdos.o
-e   CC       _gc_aes.o
-e   CC       _gc_vdi.o
  GEN      objs
make[2]: Leaving directory '/home/mikro/gemlib/.libv4e16'
-e   AR       libgemv4e16.a
-e   RANLIB   libgemv4e16.a
make[1]: Leaving directory '/home/mikro/gemlib'
```

Seeing this on WSL but it would be strange if other Linux environments behaved differently.

**Comment by th-otto** [comment]
Yes, that looks a bit strange, but is otherwise harmless. The -e is from the echo command. Some flavours of echo need it to interpret the escape sequence, some don't and just echo it as argument instead.

Edit: maybe you should also check whether POSIXLY_CORRECT is set in the enviroment. Seems to have an influence about this.

**Comment by mikrosk** [comment]
I don't see POSIXLY_CORRECT set but even if I did (just to check for a different behaviour) the outcome was the same.

I'll check at home (Arch Linux, latest versions of everything).

**Comment by th-otto** [comment]
on linux:
```
$ unset POSIXLY_CORRECT
$ /bin/echo -e foo
foo
```
```
$ export POSIXLY_CORRECT=1
$ /bin/echo -e foo
-e foo
```

You have to use /bin/echo because plain echo is the builtin from bash, which again behaves differently.

**Comment by th-otto** [comment]
Maybe you can try this patch:

```
diff --git a/RULES b/RULES
index 9782018..8b5e879 100644
--- a/RULES
+++ b/RULES
@@ -17,7 +17,11 @@ endif
 endif
 
 ifeq ($(ECHO_E),)
-ECHO_E=echo -e
+ifeq ($(shell /bin/echo -e),-e)
+ECHO_E=/bin/echo
+else
+ECHO_E=/bin/echo -e
+endif
 endif
 
 am__v_CC_0     = @$(ECHO_E) "  $(am__v_color_cc)CC$(am__v_color_off)      " $@;
```

If that doesn't work and it really bothers you, we can also just remove the color escape sequences, and use just plain echo. But i really like them ;)

**Comment by mikrosk** [comment]
Without this patch, do you see the "-e" ? Because of not, what does that mean? That my WSL's shell's echo doesn't understand "-e" while yours does?

**Comment by th-otto** [comment]
I don't see -e without this patch, because previously plain echo (the bash version) was used. Maybe your bash on WSL is different, or you are using ksh or similar?

**Comment by mikrosk** [comment]
Hmm, I remember from the old times that Ubuntu used to have dash but not anymore apparently: `GNU bash, version 5.1.16(1)-release-(x86_64-pc-linux-gnu)`. (I have 22.04.1 in my WSL container)

**Comment by mikrosk** [comment]
Oh wait. It's /bin/sh which is used, not /bin/bash. And indeed, /bin/sh points to dash. And indeed `make SHELL=/bin/bash` fixes the problem (even without your patch).

But I think your patch should be applied anyway, there's no deeper reason why gemlib shouldn't use any generic `sh`. IIRC, mintlib needs bash for some more complex operations.

**Comment by mikrosk** [comment]
Yep, verified, your patch does fix it even without `SHELL=/bin/bash`.
