### ISSUE TITLE
Make "doc" spits out a lot of warnings

### ISSUE THREAD

**Issue by th-otto** [mikrosk/lib#22]
As title says. With recent doxygen version we get lots of warnings. Any volunteer to fix that? ;)

**Comment by mikrosk** [comment]
while on the subject, _publishing_ that output would be also a good idea. :) Something similar as we do with tos.hyp via `gh-pages`.

**Comment by th-otto** [comment]
I certainly hope that all documentation contained here is already available in tos.hyp, so this might be just redundant. But of course that could be checked, too.

**Comment by mikrosk** [comment]
The purpose of doxygen comments isn't only documenting an API but also functions or modules. But yeah, in our case those two really overlap. But since we already have it... perhaps it would also motivate others to fix it if it was visibly published.

**Comment by xdelatour** [comment]
I think for most people tos.hyp is the single source of truth. Who is aware of the existence of the doxygen documentation?

**Comment by th-otto** [comment]
Well i think it wouldn't be hard to publish it somewhere,  maybe a link in freemint.github.io will do. I also didn't check yet whether the warnings cause any strangeness in the generated output, but at least i think that should be fixed first.

Maybe not all of the warnings can be fixed. Seems that some depend on how doxygen itself was build, and that might vary between systems.

**Comment by xdelatour** [comment]
> Maybe not all of the warnings can be fixed. Seems that some depend on how doxygen itself was build, and that might vary between systems.

[doxygen_fix3.patch.txt](https://github.com/freemint/gemlib/files/11010827/doxygen_fix3.patch.txt)

I changed only comments, not code except for `extern short gl_apid, gl_ap_version;` in `gem.h`. Two lines are required, else Doxygen can't find the right comment.

Removed deprecated option from Doxyfile.in. Added description for some functions (vs_crop...). Fixed a lot of warnings about undocumented variable/structures...

No more warning on my setup (doxygen 1.9.4).

**Comment by th-otto** [comment]
Wow nice, thank you! I still get some deprecation warnings, but these are probably because of different doxygen versions (1.9.6) or different distro (SuSE Tumbleweed)

**Comment by mikrosk** [comment]
I guess the simplest thing to do would be to publish it as https://freemint.github.io/gemlib ? (i.e. creating a `gh-pages` branch here in this repo).

**Comment by xdelatour** [comment]
> I still get some deprecation warnings, but these are probably because of different doxygen versions (1.9.6) or different distro (SuSE Tumbleweed)

Indeed, details are available in the [changelog](https://www.doxygen.nl/manual/changelog.html). Since 1.9.5:
- FORMULA_TRANSPARENT and DOT_TRANSPARENT have become obsolete
- DOT_FONTNAME and DOT_FONTSIZE have been replaced be more generic options

FORMULA_TRANSPARENT and DOT_TRANSPARENT can be removed but I don't know the result of the migration from old values of DOT_FONTNAME and DOT_FONTSIZE.

**Comment by th-otto** [comment]
I would leave it at it is. Replacing DOT_FONTNAME by newer options has the risk of failing when running with doxygen versions. I think we should stick atleast to the version installed on the github runner (ubuntu 22.04) which seems do be 1.9.1
